# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5c4f72e76bb62ffc4c8074c7c71f5173b56be5913428bf3dfe42e3aaaa8f31231acf1bcfc4b6f17748b30c4fe6992b8d6b7a3eb40d7dd65ee6cd0c0e4a8508e1

test:
  secret_key_base: 9014321cbae13b698ce5f8b16c2d90cb0364f13eaa3dc9798eca55413df16ebeda8ca9415b9938bb4d9beb54f44b7a2314c46d1034292a67074da9249fe045f4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
